name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i -r

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'eu-central-1'

    - name: Set Slack Secrets
      run: |
        cd beconnected-apex-homework-sst2
        npx sst secrets set SLACK_BOT_TOKEN ${{ secrets.SLACK_BOT_TOKEN }}
        npx sst secrets set SLACK_SIGNING_SECRET ${{ secrets.SLACK_SIGNING_SECRET }}
        npx sst secrets set SLACK_CHANNEL_ID ${{ secrets.SLACK_CHANNEL_ID }}

    - name: Deploy to Production
      run: |
        cd beconnected-apex-homework-sst2
        pnpm sst deploy --stage prod

    - name: Wait for 2 minutes
      run: sleep 120

    - name: Destroy Deployed Resources
      run: |
        cd beconnected-apex-homework-sst2
        pnpm sst remove --stage prod

    # Optionally, include additional steps for notifications, logging, etc.
